version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: luis
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      DB_USER: luis
      DB_PASSWORD: 123
      DB_HOST: postgres
      DB_NAME: test_db
      DB_PORT: 5432

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata: